[build.environment]
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.147.1"
NODE_VERSION = "22"
TZ = "Asia/Tokyo"

[build]
publish = "public"
command = "git submodule update --init && git config core.quotepath false && hugo --gc --minify"

